### ISSUE TITLE
Missing original export name with "inline" wit interface

### ISSUE THREAD

**Issue by kajacx** [bytecodealliance/jco#110]
## Summary

When I have a wasm component with a wit world that has "inline interfaces" (see bellow), when I transpile it with `jco transpile component.wasm --instantiation -o out-dir`, the generated TS bindings for the exported "inline interface" are wrong. Other TS types seem to be correct.

## Full example

Full reproducible example can be found [here](https://github.com/kajacx/wasm-playground/tree/wit-bindgen-inline-interface-wrong-ts), see the [`plugin-rust`](https://github.com/kajacx/wasm-playground/tree/wit-bindgen-inline-interface-wrong-ts/plugin-rust) guest and [`runtime-rust-web`](https://github.com/kajacx/wasm-playground/tree/wit-bindgen-inline-interface-wrong-ts/runtime-rust-web) host.

## Wit file
```wit
package example:protocol

interface host-imports {
  print-line: func(msg: string)
}

interface guest-exports {
  run: func()
}

world my-world {
  import host-imports
  export guest-exports

  import inline-imports: interface {
    add-one: func(num: s32) -> s32
  }
  export inline-exports: interface {
    add-three: func(num: s32) -> s32
  }
}
```

## Generated TS bindings
```ts
export interface Root {
  'example:protocol/guest-exports': typeof ExportsExampleProtocolGuestExports,
  'inline-exports': typeof ExportsInlineExports,
  guestExports: typeof ExportsExampleProtocolGuestExports,
  inlineExports: typeof ExportsInlineExports,
}
```

## Actual behaviour

The actual "instance" object is missing the `'inline-exports'` object, it only has `inlineExports`.

Ideally, it would have both to make it consistent with how "named" exports also have both variants.

## Edit

I changed the name, because it seems that the TS bindings are "correct" and the JS code is wrong. In other words, it would be better to update the JS code to match the TS bindings and not the other way around.

**Comment by guybedford** [comment]
Thanks for pointing out this disparity! None of this is set in stone at all, and we are working out these conventions, but the complexity here is that the component model very much does specify that language specific naming conventions should be used where appropriate. Ie conversion from kebab to camel case.

The mental model I use here is to think of the interface names (with a `:`) as in "canonical interface space" but to think of normal exports as in "kebab name space" that can be converted into "camel case space" because that is what you would use in JS. The set of exports is then a union of these spaces with aliases into the canonical interface space but not the kebab name space.

That is, if we did not have qualified namespace interface names, then all exports would be camel case. It is only in the qualified namespace case that we need that qualified id, as the non canonical interface "kebab name" is not a qualified name in the same sense.

Therefore, I'm open to alternatives, but given the above I think we should rather match the types here to the JS, as opposed to the other way around.

**Comment by guybedford** [comment]
Closing for the reasons described in https://github.com/bytecodealliance/jco/issues/110#issuecomment-1644321422.
