### ISSUE TITLE
Get in touch at WASMCON

### ISSUE THREAD

**Issue by dbaeumer** [bytecodealliance/jco#140]
Hi,

I am a developer on the VS Code team and I am working on adding WASM-WASI support to VS Code. Our current implementation is based on WASI preview 1 and there is a [blog post](https://code.visualstudio.com/blogs/2023/06/05/vscode-wasm-wasi) describing its state.

Over the summer I looked into supporting the new component model and WASI preview 2 inside VS Code and I made quite some progress. I will attend WASMCON in Bellevue. I saw that some of you participate as well and I would really like to meet you in person there to discuss, if there are synergies between what you are working on and what I am doing.

Here is what I have been working on so far:

- implemented the canonical ABI as described here: https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md. The corresponding TypeScript implementation can be found here: https://insiders.vscode.dev/github/microsoft/vscode-wasi/blob/dbaeumer/monetary-ox-cyan/wasm-component-model/src/common/componentModel.ts#L1

- implemented a Wit parser in TS. Major reason is that I have limited Rust skills :-). The grammar and AST are here: https://insiders.vscode.dev/github/microsoft/vscode-wasi/blob/dbaeumer/monetary-ox-cyan/wasm-component-model/src/tools/wit.pegjs#L1 and https://insiders.vscode.dev/github/microsoft/vscode-wasi/blob/dbaeumer/monetary-ox-cyan/wasm-component-model/src/tools/wit-ast.ts#L1

- a code generator that emits TypeScript code for Wit input files together with a meta model to actually handle storing, loading, lowering and lifting of user defined data types generically. It also has meta information for function signatures to handle lifting of function params and lowering of results. The emitted TypeScript doesn't conform fully to the proposal how the ABI should be mapped to JS (see https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md#js-api). Main reason was to leverage TypeScript as much as possible.

- I also generated TypeScript code for some of the WASI packages. Example code, including the meta model, can be found here: https://insiders.vscode.dev/github/microsoft/vscode-wasi/blob/dbaeumer/monetary-ox-cyan/wasi/src/clocks/monotonic-clock.ts#L1

Hope we can get in touch at WASMCON.

Best Regards

Dirk

**Comment by ricochet** [comment]
@dbaeumer if you are available, I also strongly recommend attending https://bytecodealliance.org/articles/announcing-componentize-the-world where @guybedford will be leading the workgroup around the JS ecosystem.

**Comment by tschneidereit** [comment]
As Bailey said, it'd be fantastic if you could join us for that event! What you're describing sounds extremely cool, and exactly like one of the things we mean when talking about componentizing the world 😊

**Comment by dbaeumer** [comment]
@ricochet @tschneidereit I already signed up for the workshop. Looking forward to seeing you there.

**Comment by guybedford** [comment]
Hey @dbaeumer, I finally had a read through the links you posted here and this is very exciting work, thanks for posting here! I was working last week on some demo material for my talk and ended up using a similar console style demo to show some of the possibilities. You likely won't believe me at this point that it was before I read through all your links! It's a great use case. The TypeScript generation you have is looking fantastic as well. One issue we have is we have some subtle differences between lifting and lowering types for JavaScript due to slight differences in the coercions, which seemed worth capturing (ie inputs from JS are more flexibly typed than outputs). It would be great to swap notes on the TS generation, and of course your use cases focus some great considerations for the work that would be great to discuss. Look forward to meeting then.

**Comment by guybedford** [comment]
There were some really great conversations here all around, nice to see the various follow-ups!
