### ISSUE TITLE
`jco run` appears to execute a world-writable file

### ISSUE THREAD

**Issue by BrianJDrake** [bytecodealliance/jco#180]
https://github.com/bytecodealliance/jco/blob/cbc396d909e5a493e4ea62340b3e7a61ac0c79b7/src/cmd/run.js#L83-L85

This looks like an extraordinary vulnerability, even for experimental software. It's so extraordinary that I feel like I must be misinterpreting this code; however, it has no comments to help me.

The file is within a (supposedly) private directory. This fact is not verified by this code (#181), and even if it were, I am not sure what protection it would give.

In any case, what is the point of this `chmod` call?

**Comment by guybedford** [comment]
> This looks like an extraordinary vulnerability, even for experimental software. It's so extraordinary that I feel like I must be misinterpreting this code; however, it has no comments to help me.

This is a little bit dramatic @BrianJDrake. `jco run` is a Node.js runner which runs components in an unrestricted context. This is no different to the security model of any unsandboxed platform like Node.js itself.

Since `jco run` does not provide any type of reduced permissions system, it does run with full privileges. Having reduced permissions in future would be a very interesting project to explore. Contributors who are interested in this type of work would be very much welcomed.

**Comment by BrianJDrake** [comment]
@guybedford You point out that `jco run` (and Node.js itself) do not create security boundaries. That is true, but that is a separate issue.

Even though `jco run` does not create security boundaries of its own, it should respect existing security boundaries, including filesystem permissions. In fact, it does the exact opposite: by setting a file mode of `0o777`, it explicitly bypasses an existing security boundary. It does so in the worst possible way, by giving all users (including possibly untrusted users) the ability to make arbitrary changes to code it is about to execute.

**Comment by guybedford** [comment]
Let's move this into https://github.com/bytecodealliance/jco/issues/183.
