### ISSUE TITLE
Current implementation of the shim is limiting

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/jco#303]
I would like to ship, on npm, a few WASI commands that all need to use the virtualized filesystem. These commands are essentially pure functions that happen to be implemented in C++.

The browser shim implementation is perfect for this: I have a virtualized filesystem and arguments. The Node shim implementation seems to require the use of the host filesystem. It doesn't seem possible to use the virtualized filesystem from the browser implementation if I'm running on Node, limiting the usefulness of publishing an npm package.

It seems that the selection of the provided environment is done in a way that cannot be influenced by the code that uses the transpiled module. Am I missing anything?

(This seems related to https://github.com/bytecodealliance/jco/issues/302)

**Comment by pchickey** [comment]
I believe that, if you want to provide your application with its own virtual (read-only) filesystem and environment flags, you want to use `[wasi-virt](https://github.com/bytecodealliance/WASI-Virt)` to produce a component providing those that it composes with.

wasi-virt is currently not compatible with jco because it is stuck on an older version of the WASI preview 2 wits. It needs to be updated but I believe everyone who has contributed to it is working on other things right this moment

**Comment by whitequark** [comment]
> I believe that, if you want to provide your application with its own virtual (read-only) filesystem

I need it to be read-write because the output of the application is written to the filesystem.

> wasi-virt is currently not compatible with jco because it is stuck on an older version of the WASI preview 2 wits. It needs to be updated but I believe everyone who has contributed to it is working on other things right this moment

Yep, I just hit this problem.

**Comment by pchickey** [comment]
My understanding is that a writable host filesystem can be overlaid on a read-only virtualized filesystem, but thats a question for over in wasi-virt...

**Comment by whitequark** [comment]
I settled on reimplementing the shim entirely. See also https://github.com/bytecodealliance/jco/issues/302#issuecomment-1846618799, which was the other half of the puzzle.

**Comment by whitequark** [comment]
@pchickey Take a look at https://github.com/YoWASP/yosys/pull/28 if you'd like. I think my shim is fairly complete and in places might even do things the shim here doesn't. (I got a weird issue where `scandir` apparently passes `..` to `openAt` which doesn't make a lot of sense...)

**Comment by guybedford** [comment]
@whitequark I really like your approach here - perhaps we should take what we have of a "browser implementation" and instead call it a "virtual JS implementation", and make it available always as an instantiation workflow as you have done. Obviously WASI-Virt is the ideal for this, because it saves implementing this in every ecosystem, but until we have that I definitely appreciate it's useful, and the browser implementation is kinda almost there. Does that sound like a sensible approach to you? Any other suggestions for the project very welcome.

**Comment by whitequark** [comment]
@guybedford That would be fantastic, and very useful to me.

Will WASI-Virt ever handle the case of a writable filesystem that is accessed by the embedder? If not the need for this feature will remain after WASI-Virt is done.

**Comment by guybedford** [comment]
WASI-Virt will get support for dynamic filesystems yes, it's just not been prioritized so far. Certainly this entire virtualization feature should be entirely subsumed by WASI-Virt though, since that offers the same virtualization system. But there's no reason we can't offer some flexibility by having options too.

**Comment by whitequark** [comment]
Got it! That would be nice.

**Comment by whitequark** [comment]
@pchickey @guybedford I've productized my JS runtime for YoWASP and published first non-experimental Yosys builds
- https://github.com/YoWASP/runtime-js
- https://www.npmjs.com/package/@yowasp/yosys
Take a look :)
